mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location:  classpath:/mybatis/mybatis-config.xml
  type-aliases-package: com.gbdpcloud.bayes.entity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bayes?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

filepath:
  model: models
  input: inputs
  datasets: /Users/ziqiangyuan/Downloads/bayes-new/